name: Publish @deriv-com/derivatives-charts
on:
    workflow_dispatch:

jobs:
    build_and_publish_derivatives_charts:
        runs-on: Ubuntu-latest
        permissions:
            contents: write
        steps:
            - name: Checkout derivatives-charts
              uses: 'deriv-com/derivatives-charts/.github/actions/checkout@master'
              with:
                  repository: 'deriv-com/derivatives-charts'
                  path: derivatives-charts
                  ref: master

            - name: Custom flutter-chart
              id: flutter_chart
              uses: 'deriv-com/derivatives-charts/.github/actions/checkout@master'
              with:
                  repository: 'deriv-com/flutter-chart'
                  path: flutter-chart
                  # temporary reference to an old branch
                  ref: fe-changes
            - uses: subosito/flutter-action@62f096cacda5168a3bd7b95793373be14fa4fbaf
              with:
                  flutter-version: '3.10.6'
                  channel: 'stable'
                  cache: true
            - name: Build flutter
              run: |
                  cd derivatives-charts/chart_app
                  flutter pub get
                  flutter build web --web-renderer html --release

            - name: Setup node
              uses: actions/setup-node@b39b52d1213e96004bfcb1c61a8a6fa8ab84f3e8
              with:
                  node-version: 20.x

            - name: Setup derivatives-charts
              run: cd derivatives-charts && npm install

            - name: Build derivatives-charts
              run: cd derivatives-charts && npm run build
            - name: Release derivatives-charts
              env:
                  CI: true
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
              run: cd derivatives-charts && npx semantic-release
